### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by budparr** [sonnetmedia/retroreport#110]
- [ ] Update font files

In the site's files:

- [ ] (config.toml) change `baseurl` to whatever the final domain is, including the www and https protocol (e.g. https://www.example.com)
- [ ] Test production HUGO_ENV locally (run `HUGO_ENV=production hugo server --verbose`)
- [ ] (netlify.toml) change the HUGO_ENV in the production env to "production"

---

At domain registrar or wherever the NS records are managed, update the following:

- [ ] CNAME: "www" to "site_name.netlify.com"
- [ ] A: @ to 104.198.14.52

For more information, see: https://www.netlify.com/docs/custom-domains/#dns-configuration

---

Once the domain is set, (Netlify: /site settings/domain management/)
- [ ] turn off site control if there was a password set.
- [ ] change the domain name in the Netlify control panel (../custom domain).
- [ ] provision Lets Encrypt certificate (/domain).
- [ ] force TLS connecttions
- [ ] Set up notifications to Slack, or email.

---
- [ ] Add headers info to config (placeholder for more info on this)
- [ ] Review headers for proper data
- [ ] Review content security policy items.
- [ ] Create/Retreive tracking ID and to `googleAnalytics` in config
- [ ] Add manifest.json and favicons (can generate here: https://realfavicongenerator.net/)

---
Test setttings:
- [ ] View the live production site and make sure the word `production` shows up as a body class and make sure open graph and other social tags are rendering.
- [ ] View a sample page on Facebook's object debug https://developers.facebook.com/tools/debug/og/object/
